import type { Material } from "../schemas/material.ts";

const POLYHAVEN_ASSET_URL = "https://polyhaven.com/a";
const AMBIENTCG_ASSET_URL = "https://ambientcg.com/view?id=";

// Texture files are imported in a later phase, so every seed material starts as "pending" with empty maps
// and renders with its fallback colour until then. tileSize is the real-world size of one texture tile
// (Poly Haven publishes it as `dimensions`, in millimetres).
export const SEED_MATERIALS: Material[] = [
  {
    id: "mat_oak_floorboards",
    name: "Eichendielen",
    source: "polyhaven",
    sourceId: "oak_wood_planks",
    license: "CC0",
    sourceUrl: `${POLYHAVEN_ASSET_URL}/oak_wood_planks`,
    maps: {},
    importStatus: "pending",
    tileSize: 1.2,
    tint: null,
    roughnessFactor: 0.6,
    metalnessFactor: null,
    fallbackColor: "#b58a5c",
  },
  {
    id: "mat_tiles",
    name: "Keramikfliesen, beige",
    source: "polyhaven",
    sourceId: "interior_tiles",
    license: "CC0",
    sourceUrl: `${POLYHAVEN_ASSET_URL}/interior_tiles`,
    maps: {},
    importStatus: "pending",
    tileSize: 1.9,
    tint: null,
    roughnessFactor: 0.45,
    metalnessFactor: null,
    fallbackColor: "#d6cdbd",
  },
  {
    id: "mat_wall_paint",
    name: "Wandfarbe, warmweiß",
    source: "polyhaven",
    sourceId: "beige_wall_001",
    license: "CC0",
    sourceUrl: `${POLYHAVEN_ASSET_URL}/beige_wall_001`,
    maps: {},
    importStatus: "pending",
    tileSize: 3,
    tint: "#fbf7ee",
    roughnessFactor: 0.95,
    metalnessFactor: null,
    fallbackColor: "#ece6da",
  },
  {
    id: "mat_linen",
    name: "Leinen, natur",
    source: "polyhaven",
    sourceId: "hessian_380",
    license: "CC0",
    sourceUrl: `${POLYHAVEN_ASSET_URL}/hessian_380`,
    maps: {},
    importStatus: "pending",
    tileSize: 0.27,
    tint: "#efe4d0",
    roughnessFactor: 1,
    metalnessFactor: null,
    fallbackColor: "#c4b79f",
  },
  {
    id: "mat_oak",
    name: "Eiche, geölt",
    source: "polyhaven",
    sourceId: "oak_veneer_01",
    license: "CC0",
    sourceUrl: `${POLYHAVEN_ASSET_URL}/oak_veneer_01`,
    maps: {},
    importStatus: "pending",
    tileSize: 1.83,
    tint: null,
    roughnessFactor: 0.65,
    metalnessFactor: null,
    fallbackColor: "#a77b4f",
  },
  {
    // Brass is a brushed-steel texture with a brass tint; ambientCG ships no tileable brass.
    id: "mat_brass",
    name: "Messing, gebürstet",
    source: "ambientcg",
    sourceId: "Metal012",
    license: "CC0",
    sourceUrl: `${AMBIENTCG_ASSET_URL}Metal012`,
    maps: {},
    importStatus: "pending",
    tileSize: 1,
    tint: "#d4aa57",
    roughnessFactor: 0.5,
    metalnessFactor: 1,
    fallbackColor: "#b8923e",
  },
];
