import { assetContentHash, materialContentHash } from "../hash.ts";
import type { Asset } from "../schemas/asset.ts";
import type { Document } from "../schemas/document.ts";
import type { Material } from "../schemas/material.ts";
import { SEED_ASSETS } from "./assets.ts";
import { SEED_DOCUMENT } from "./document.ts";
import { SEED_MATERIALS } from "./materials.ts";

const escapeQuotes = (text: string): string => text.replaceAll("'", "''");
const text = (value: string | null | undefined): string => (value == null ? "null" : `'${escapeQuotes(value)}'`);
const jsonb = (value: unknown): string => `'${escapeQuotes(JSON.stringify(value))}'::jsonb`;
const number = (value: number | null | undefined): string => (value == null ? "null" : String(value));

function insertStatement(table: string, columns: string[], values: string[]): string {
  return [
    `insert into public.${table} (${columns.join(", ")})`,
    `values (${values.join(", ")})`,
    "on conflict (id) do nothing;",
  ].join("\n");
}

function materialInsert(material: Material): string {
  return insertStatement(
    "materials",
    [
      "id", "name", "source", "source_id", "license", "source_url", "maps", "import_status", "tile_size",
      "tint", "roughness_factor", "metalness_factor", "fallback_color", "content_hash",
    ],
    [
      text(material.id), text(material.name), text(material.source), text(material.sourceId), text(material.license),
      text(material.sourceUrl), jsonb(material.maps), text(material.importStatus), number(material.tileSize),
      text(material.tint), number(material.roughnessFactor), number(material.metalnessFactor),
      text(material.fallbackColor), text(materialContentHash(material)),
    ],
  );
}

function assetInsert(asset: Asset): string {
  return insertStatement(
    "assets",
    ["id", "name", "category", "params", "parts", "reference_images", "content_hash", "version"],
    [
      text(asset.id), text(asset.name), text(asset.category), jsonb(asset.params), jsonb(asset.parts),
      jsonb(asset.referenceImages), text(assetContentHash(asset)), "1",
    ],
  );
}

function documentInsert(document: Document): string {
  return insertStatement(
    "documents",
    ["id", "name", "source", "apartment", "items", "lighting", "version"],
    [
      text(document.id), text(document.name), text(document.source), jsonb(document.apartment),
      jsonb(document.items), jsonb(document.lighting), "1",
    ],
  );
}

export function buildSeedSql(): string {
  const statements = [
    "-- Generated by packages/core/scripts/write-seed.ts from packages/core/src/seed. Do not edit by hand.",
    ...SEED_MATERIALS.map(materialInsert),
    ...SEED_ASSETS.map(assetInsert),
    documentInsert(SEED_DOCUMENT),
    `update public.app_state set active_document_id = ${text(SEED_DOCUMENT.id)} where id = 1;`,
  ];
  return `${statements.join("\n\n")}\n`;
}
